/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) multirotor_rate_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};

/* multirotor_rate_model_expl_ode_fun:(i0[10],i1[4],i2[0])->(o0[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+7, w2, *w3=w+11, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+28, *w18=w+31, *w19=w+34, *w20=w+37, *w21=w+46, *w22=w+55, *w23=w+59, *w24=w+63, *w25=w+67, *w26=w+71, *w27=w+75, *w28=w+91;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @0 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w0);
  /* #3: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #4: @2 = 1 */
  w2 = 1.;
  /* #5: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w3);
  /* #6: @4 = @3[2] */
  for (rr=(&w4), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #7: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #8: @6 = @3[3] */
  for (rr=(&w6), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #9: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #10: @8 = (@5+@7) */
  w8  = (w5+w7);
  /* #11: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #12: @8 = (@2-@8) */
  w8  = (w2-w8);
  /* #13: @9 = @3[1] */
  for (rr=(&w9), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #14: @10 = (@9*@4) */
  w10  = (w9*w4);
  /* #15: @11 = @3[0] */
  for (rr=(&w11), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #16: @12 = (@11*@6) */
  w12  = (w11*w6);
  /* #17: @13 = (@10-@12) */
  w13  = (w10-w12);
  /* #18: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #19: @14 = (@9*@6) */
  w14  = (w9*w6);
  /* #20: @15 = (@11*@4) */
  w15  = (w11*w4);
  /* #21: @16 = (@14+@15) */
  w16  = (w14+w15);
  /* #22: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #23: @17 = horzcat(@8, @13, @16) */
  rr=w17;
  *rr++ = w8;
  *rr++ = w13;
  *rr++ = w16;
  /* #24: @17 = @17' */
  /* #25: @10 = (@10+@12) */
  w10 += w12;
  /* #26: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #27: @12 = sq(@9) */
  w12 = casadi_sq( w9 );
  /* #28: @7 = (@12+@7) */
  w7  = (w12+w7);
  /* #29: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #30: @7 = (@2-@7) */
  w7  = (w2-w7);
  /* #31: @4 = (@4*@6) */
  w4 *= w6;
  /* #32: @11 = (@11*@9) */
  w11 *= w9;
  /* #33: @9 = (@4-@11) */
  w9  = (w4-w11);
  /* #34: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #35: @18 = horzcat(@10, @7, @9) */
  rr=w18;
  *rr++ = w10;
  *rr++ = w7;
  *rr++ = w9;
  /* #36: @18 = @18' */
  /* #37: @14 = (@14-@15) */
  w14 -= w15;
  /* #38: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #39: @4 = (@4+@11) */
  w4 += w11;
  /* #40: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #41: @12 = (@12+@5) */
  w12 += w5;
  /* #42: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #43: @2 = (@2-@12) */
  w2 -= w12;
  /* #44: @19 = horzcat(@14, @4, @2) */
  rr=w19;
  *rr++ = w14;
  *rr++ = w4;
  *rr++ = w2;
  /* #45: @19 = @19' */
  /* #46: @20 = horzcat(@17, @18, @19) */
  rr=w20;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  /* #47: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #48: @14 = 0 */
  w14 = 0.;
  /* #49: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #50: @17 = vertcat(@14, @14, @4) */
  rr=w17;
  *rr++ = w14;
  *rr++ = w14;
  *rr++ = w4;
  /* #51: @1 = mac(@21,@17,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #52: @0 = (@0+@1) */
  for (i=0, rr=w0, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #53: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #54: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #55: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #56: @0 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+1 : 0, 3, w0);
  /* #57: @2 = @0[0] */
  for (rr=(&w2), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #58: @12 = (-@2) */
  w12 = (- w2 );
  /* #59: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #60: @11 = (-@5) */
  w11 = (- w5 );
  /* #61: @15 = @0[2] */
  for (rr=(&w15), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #62: @10 = (-@15) */
  w10 = (- w15 );
  /* #63: @23 = horzcat(@14, @12, @11, @10) */
  rr=w23;
  *rr++ = w14;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w10;
  /* #64: @23 = @23' */
  /* #65: @24 = horzcat(@2, @14, @15, @11) */
  rr=w24;
  *rr++ = w2;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w11;
  /* #66: @24 = @24' */
  /* #67: @25 = horzcat(@5, @10, @14, @2) */
  rr=w25;
  *rr++ = w5;
  *rr++ = w10;
  *rr++ = w14;
  *rr++ = w2;
  /* #68: @25 = @25' */
  /* #69: @26 = horzcat(@15, @5, @12, @14) */
  rr=w26;
  *rr++ = w15;
  *rr++ = w5;
  *rr++ = w12;
  *rr++ = w14;
  /* #70: @26 = @26' */
  /* #71: @27 = horzcat(@23, @24, @25, @26) */
  rr=w27;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  /* #72: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #73: @22 = mac(@28,@3,@22) */
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w28+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #74: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #75: output[0][2] = @22 */
  if (res[0]) casadi_copy(w22, 4, res[0]+6);
  return 0;
}

CASADI_SYMBOL_EXPORT int multirotor_rate_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int multirotor_rate_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int multirotor_rate_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multirotor_rate_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int multirotor_rate_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void multirotor_rate_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void multirotor_rate_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void multirotor_rate_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int multirotor_rate_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int multirotor_rate_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real multirotor_rate_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multirotor_rate_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* multirotor_rate_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multirotor_rate_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* multirotor_rate_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int multirotor_rate_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 107;
  return 0;
}

CASADI_SYMBOL_EXPORT int multirotor_rate_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 107*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
