# # Use the base image
FROM px4uxrce_img:v4.1

# RUN pip install setuptools==58.0.0

# # RUN apt-get update && apt-get install -y nano && apt-get install ros-humble-ros1-bridge
# # RUN apt upgrade -y

# FROM px4uxrce:v4

# RUN apt-get update && apt-get install -y \
#     ros-humble-cv-bridge \
#     ros-humble-image-transport \
#     ros-humble-diagnostic-updater \
#     ros-humble-rviz2 \
#     ros-humble-geographic-msgs \
#     usbutils \
#     libx11-dev \
#     libglu1-mesa-dev \
#     libglfw3-dev \
#     && rm -rf /var/lib/apt/lists/*



# Install PX4 XRCE-DDS packages
